/**
 * Configuration management for the AI Voice SOP Agent
 */

export interface AppConfig {
  server: ServerConfig;
  services: ServicesConfig;
  audio: AudioConfig;
  ai: AIConfig;
  export: ExportConfig;
  logging: LoggingConfig;
}

export interface ServerConfig {
  port: number;
  host: string;
  cors: CorsConfig;
  rateLimit: RateLimitConfig;
}

export interface CorsConfig {
  origin: string | string[];
  credentials: boolean;
  methods: string[];
}

export interface RateLimitConfig {
  windowMs: number;
  maxRequests: number;
}

export interface ServicesConfig {
  speechToText: SpeechToTextConfig;
  textToSpeech: TextToSpeechConfig;
  storage: StorageConfig;
}

export interface SpeechToTextConfig {
  provider: 'google' | 'azure' | 'aws';
  apiKey: string;
  language: string;
  confidenceThreshold: number;
  maxAudioDuration: number;
}

export interface TextToSpeechConfig {
  provider: 'google' | 'azure' | 'aws';
  apiKey: string;
  defaultVoice: string;
  audioFormat: string;
  sampleRate: number;
}

export interface StorageConfig {
  type: 'local' | 'cloud';
  path: string;
  maxFileSize: number;
  allowedFormats: string[];
}

export interface AudioConfig {
  sampleRate: number;
  channels: number;
  bitDepth: number;
  maxRecordingDuration: number;
  silenceThreshold: number;
  noiseReduction: boolean;
}

export interface AIConfig {
  conversationModel: string;
  sopGenerationModel: string;
  maxTokens: number;
  temperature: number;
  maxIterations: number;
}

export interface ExportConfig {
  supportedFormats: string[];
  defaultTemplate: string;
  maxDocumentSize: number;
  watermark: WatermarkConfig;
}

export interface WatermarkConfig {
  enabled: boolean;
  text: string;
  opacity: number;
  position: 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right' | 'center';
}

export interface LoggingConfig {
  level: 'error' | 'warn' | 'info' | 'debug';
  format: 'json' | 'simple';
  file: FileLoggingConfig;
  console: ConsoleLoggingConfig;
}

export interface FileLoggingConfig {
  enabled: boolean;
  path: string;
  maxSize: string;
  maxFiles: number;
}

export interface ConsoleLoggingConfig {
  enabled: boolean;
  colorize: boolean;
}

/**
 * Default configuration values
 */
export const defaultConfig: AppConfig = {
  server: {
    port: parseInt(process.env.PORT || '3000'),
    host: process.env.HOST || 'localhost',
    cors: {
      origin: process.env.CORS_ORIGIN || '*',
      credentials: true,
      methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
    },
    rateLimit: {
      windowMs: 15 * 60 * 1000, // 15 minutes
      maxRequests: 100
    }
  },
  services: {
    speechToText: {
      provider: (process.env.STT_PROVIDER as any) || 'google',
      apiKey: process.env.STT_API_KEY || '',
      language: process.env.STT_LANGUAGE || 'en-US',
      confidenceThreshold: parseFloat(process.env.STT_CONFIDENCE_THRESHOLD || '0.7'),
      maxAudioDuration: parseInt(process.env.STT_MAX_DURATION || '300') // 5 minutes
    },
    textToSpeech: {
      provider: (process.env.TTS_PROVIDER as any) || 'google',
      apiKey: process.env.TTS_API_KEY || '',
      defaultVoice: process.env.TTS_DEFAULT_VOICE || 'en-US-Standard-A',
      audioFormat: process.env.TTS_AUDIO_FORMAT || 'mp3',
      sampleRate: parseInt(process.env.TTS_SAMPLE_RATE || '22050')
    },
    storage: {
      type: (process.env.STORAGE_TYPE as any) || 'local',
      path: process.env.STORAGE_PATH || './storage',
      maxFileSize: parseInt(process.env.MAX_FILE_SIZE || '10485760'), // 10MB
      allowedFormats: ['pdf', 'docx', 'html', 'md']
    }
  },
  audio: {
    sampleRate: parseInt(process.env.AUDIO_SAMPLE_RATE || '16000'),
    channels: parseInt(process.env.AUDIO_CHANNELS || '1'),
    bitDepth: parseInt(process.env.AUDIO_BIT_DEPTH || '16'),
    maxRecordingDuration: parseInt(process.env.MAX_RECORDING_DURATION || '600'), // 10 minutes
    silenceThreshold: parseFloat(process.env.SILENCE_THRESHOLD || '0.01'),
    noiseReduction: process.env.NOISE_REDUCTION === 'true'
  },
  ai: {
    conversationModel: process.env.CONVERSATION_MODEL || 'gpt-4',
    sopGenerationModel: process.env.SOP_MODEL || 'gpt-4',
    maxTokens: parseInt(process.env.MAX_TOKENS || '4000'),
    temperature: parseFloat(process.env.AI_TEMPERATURE || '0.7'),
    maxIterations: parseInt(process.env.MAX_ITERATIONS || '5')
  },
  export: {
    supportedFormats: ['pdf', 'docx', 'html', 'md'],
    defaultTemplate: process.env.DEFAULT_TEMPLATE || 'standard',
    maxDocumentSize: parseInt(process.env.MAX_DOCUMENT_SIZE || '52428800'), // 50MB
    watermark: {
      enabled: process.env.WATERMARK_ENABLED === 'true',
      text: process.env.WATERMARK_TEXT || 'Generated by AI Voice SOP Agent',
      opacity: parseFloat(process.env.WATERMARK_OPACITY || '0.3'),
      position: (process.env.WATERMARK_POSITION as any) || 'bottom-right'
    }
  },
  logging: {
    level: (process.env.LOG_LEVEL as any) || 'info',
    format: (process.env.LOG_FORMAT as any) || 'json',
    file: {
      enabled: process.env.FILE_LOGGING === 'true',
      path: process.env.LOG_FILE_PATH || './logs/app.log',
      maxSize: process.env.LOG_MAX_SIZE || '10m',
      maxFiles: parseInt(process.env.LOG_MAX_FILES || '5')
    },
    console: {
      enabled: process.env.CONSOLE_LOGGING !== 'false',
      colorize: process.env.LOG_COLORIZE !== 'false'
    }
  }
};

/**
 * Get configuration with environment variable overrides
 */
export function getConfig(): AppConfig {
  return defaultConfig;
}

/**
 * Validate configuration
 */
export function validateConfig(config: AppConfig): string[] {
  const errors: string[] = [];
  const isDevelopment = process.env.NODE_ENV === 'development' || process.env.NODE_ENV === undefined;

  // In development mode, API keys are optional (services will use mock implementations)
  if (!isDevelopment) {
    if (!config.services.speechToText.apiKey) {
      errors.push('Speech-to-Text API key is required');
    }

    if (!config.services.textToSpeech.apiKey) {
      errors.push('Text-to-Speech API key is required');
    }
  }

  if (config.server.port < 1 || config.server.port > 65535) {
    errors.push('Server port must be between 1 and 65535');
  }

  if (config.services.speechToText.confidenceThreshold < 0 || config.services.speechToText.confidenceThreshold > 1) {
    errors.push('Speech-to-Text confidence threshold must be between 0 and 1');
  }

  return errors;
}